name: visemaps
description: A new Flutter project.

publish_to: 'none'

version: 1.0.2

environment:
  sdk: ">=2.17.5 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  cupertino_icons: ^1.0.2
  path_provider: ^2.0.11
  vector_math: ^2.1.2
  firebase_core: ^2.3.0
  firebase_storage: ^11.0.6
  firebase_auth: ^4.1.5
  fs:
    path: fs
  go_router: ^5.2.1
  side_navigation: ^1.0.4

dev_dependencies:
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  fonts:
    - family:  LoginIcons
      fonts:
        - asset: fonts/LoginIcons.ttf