name: Deploy to Firebase Hosting
'on':
  push:
    branches:
      - master
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'
          token: ${{secrets.GITHUB_TOKEN}}
      - name: Install Flutter
        uses: britannio/action-install-flutter@v1.1
      - name: Install dependencies
        run: flutter pub get
      - name: Run Flutter
        run: flutter build web --web-renderer canvaskit
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{secrets.GITHUB_TOKEN}}'
          firebaseServiceAccount: '${{secrets.FIREBASE_SERVICE_ACCOUNT_VISE_MAPS}}'
          channelId: live
          projectId: vise-maps